### ISSUE TITLE
Error in bundle install

### ISSUE THREAD

**Issue by olibrian** [hitobito/development#1]
Try setup hitobito on a brand new clear ubuntu installation. 
when running `docker-compose run rails rails db:seed wagon:seed` got errors bundle install.

```
Running bundle install
Fetching gem metadata from https://rubygems.org/.........
Bundler::PermissionError: There was an error while trying to write to
/opt/bundle/cache. It is likely that you need to grant write permissions for
that path.
An error occurred while installing rake (13.0.1), and Bundler
cannot continue.
Make sure that gem install rake -v '13.0.1' --source https://rubygems.org/
succeeds before bundling.

In Gemfile:
  activerecord-session_store was resolved to 1.1.3, which depends on
    railties was resolved to 6.0.3.2, which depends on
      rake
`
```
Any ideas?

**Comment by psunix** [comment]
just comited a fix for the user permissions. please pull.

please remove and re-add the docker volume hitobito_bundle:

`docker volume rm hitobito_bundle`

**Comment by olibrian** [comment]
Thanks for the update. Works fine, after modify the doker-compose.yml a little. See PR https://github.com/hitobito/development/pull/2

**Comment by olibrian** [comment]
Nice work!
![Screenshot from 2020-07-13 21-56-09](https://user-images.githubusercontent.com/9592347/87347547-b8b44200-c553-11ea-8434-bcc39128439b.png)
