### ISSUE TITLE
Manche hitobito-Mailings failen in Docker (PBS)

### ISSUE THREAD

**Issue by Vento-Nuenenen** [hitobito/development#10]
Manche Mailings funktionieren im Docker nicht, im Test & Prod aber schon.

Bsp. wenn sich ein TN an einem Kurs anmeldet, sollte eine Anmelde-Bestätigung gesendet werden. Funktioniert im Docker nicht.
Bsp. Abmeldung von einem Kurs klappt.

Stacktrace vom Bsp:
`
[Worker(host:fe5fa172288a pid:1)] Job Event::ApprovalRequestJob (id=187) FAILED (6 prior attempts) with ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"event/participations", :event_id=>#<Event::Participation id: 1260, event_id: 121, person_id: 449, additional_information: nil, created_at: "2020-09-27 13:20:48", updated_at: "2020-09-27 13:20:48", active: true, application_id: 248, qualified: nil, canceled_at: nil, state: "assigned", bsv_days: nil>, :group_id=>#<Event::Course id: 121, type: "Event::Course", name: "BKPS 701", number: "701", motto: "Voluptas velit odit nulla provident et sunt non mo...", cost: nil, maximum_participants: 24, contact_id: nil, description: "Repellendus recusandae nulla quo libero quos fugit...", location: "Karl-Jaspers-Str. 2\n79100\nVeraland", application_opening_at: "2020-12-21", application_closing_at: "2021-02-19", application_conditions: nil, kind_id: 3, state: "closed", priorization: true, requires_approval: true, created_at: "2020-09-27 13:20:47", updated_at: "2020-09-27 13:20:48", participant_count: 0, application_contact_id: nil, external_applications: true, applicant_count: 2, teamer_count: 5, signature: true, signature_confirmation: nil, signature_confirmation_text: nil, creator_id: nil, updater_id: nil, applications_cancelable: false, required_conta
[], hidden_contact_attrs: [], display_booking_info: true, training_days: nil, tentative_applications: false, language_de: false, language_fr: false, language_it: false, language_en: false, express_fee: nil, requires_approval_abteilung: true, requires_approval_region: false, requires_approval_kantonalverband: false, requires_approval_bund: false, expected_participants_wolf_f: nil, expected_participants_wolf_m: nil, expected_participants_pfadi_f: nil, expected_participants_pfadi_m: nil, expected_participants_pio_f: nil, expected_participants_pio_m: nil, expected_participants_rover_f: nil, expected_participants_rover_m: nil, expected_participants_leitung_f: nil, expected_participants_leitung_m: nil, canton: nil, coordinates: nil, altitude: nil, emergency_phone: nil, landlord: nil, landlord_permission_obtained: false, j_s_kind: nil, j_s_security_snow: false, j_s_security_mountain: false, j_s_security_water: false, participants_can_apply: false, participants_can_cancel: false, al_present: false, al_visiting: false, al_visiting_date: nil, coach_visiting: false, coach_visiting_date: nil, coach_confirmed: false, local_scout_contact_present: false, local_scout_contact: nil, camp_reminder_sent: false, paper_application_required: false, lagerreglement_applied: false, kantonalverband_rules_applied: false, j_s_rules_applied: false, bsv_days: nil, camp_submitted_at: nil, has_confirmations: true, parent_id: nil, allow_sub_camps: false, lft: 241, rgt: 242, contact_attrs_passed_on_to_supercamp: nil>, :locale=>#<Group::Abteilung id: 16, parent_id: 9, lft: 74, rgt: 75, name: "Chräis Chäib", short_name: nil, type: "Group::Abteilung", email: "cordell@example.org", address: "Bohnenkampsweg 56b", zip_code: 3189, town: "West Corinna", country: nil, contact_id: nil, created_at: "2020-09-27 13:17:13", updated_at: "2020-09-27 13:17:13", deleted_at: nil, layer_group_id: 16, creator_id: nil, updater_id: nil, deleter_id: nil, require_person_add_requests: false, description: nil, logo: nil, pta: false, vkp: false, pbs_material_insurance: false, website: nil, pbs_shortname: nil, bank_account: nil, application_approver_role: nil, gender: nil, try_out_day_at: nil, group_health: false>}, missing required keys: [:id]
`

**Comment by carlobeltrame** [comment]
Merci für den Report, das wurde in https://github.com/hitobito/hitobito/commit/7ab5c09942067eedf2f32205000c5765b963ebd4 gefixt.
