### ISSUE TITLE
Docker Compose: File not found

### ISSUE THREAD

**Issue by henrikmotzkus** [hitobito/development#16]
Hi there,
I tried to run your docker compose (docker-compose run rails 'rails db:seed wagon:seed') in order to build a dev environment but get the following error: 
```
### Dependency Installed:
  libtool-ltdl.x86_64 0:2.4.2-22.el7_3      unixODBC.x86_64 0:2.3.1-14.el7

Complete!
: No such file or directory
ERROR: Service 'webpack' failed to build : The command '/bin/sh -c yum localinstall -y       "https://github.com/sphinxsearch/sphinx/releases/download/2.2.11-release/sphinx-2.2.11-1.rhel7.x86_64.rpm" &&     scl enable rh-ruby26 install-nodejs &&     yum install -y python-setuptools &&     scl enable rh-ruby26 install-transifex &&     yum install ImageMagick ImageMagick-devel -y' returned a non-zero code: 127
```
My building workstation is running Windows 10 + WSL 2 + Docker for Windows.

See full output in the file

[output-docker-compose.txt](https://github.com/hitobito/development/files/6063593/output-docker-compose.txt)

**Comment by henrikmotzkus** [comment]
I discovered further that in this step the script crashes:

`scl enable rh-ruby26 install-nodejs && \`

**Comment by psunix** [comment]
Hi Henrik

it looks like 'install-nodejs' is failing. this installation script is defined here: https://github.com/hitobito/hitobito/blob/master/images/s2i/root/opt/bin/install-nodejs

I don't know anything about running docker on Windows. Is there any command in this installation script that is somehow incompatible with Windows?

**Comment by carlobeltrame** [comment]
Closing this because no further reply from reporter. Feel free to open another issue if the problem still needs to be solved.
