### ISSUE TITLE
Sending Mails to Hitobito

### ISSUE THREAD

**Issue by maede97** [hitobito/development#33]
I managed to get everything up and running, and I currently want to test the mail features out (abo). 
However, the email-adress is something like ...@localhost (which makes sense).
Mailcatcher does only catch incoming mails, which are sent for example when a user want's a password reset link. This does work.
However, is there a way to send a mail to the running hitobito application for it to be sent to the abo mailing lists?

**Comment by carlobeltrame** [comment]
I don't think there is a way to do this yet. I also asked the same thing back on the predecessor of this project in https://github.com/nxt-engineering/hitobito-docker/issues/1. Hitobito itself cannot receive emails, you'd need a local mail server for that. Hitobito could then be [configured](https://github.com/hitobito/hitobito/blob/409d87e8d2ee6fa358c997766922835f8c0c7183/doc/development/02_deployment.md#konfiguration) (RAILS_MAIL_RETRIEVER_CONFIG) to fetch emails from a catch-all inbox on that local mail server, that's how we do it in production.

**Comment by mtnstar** [comment]
we do have a development test inbox (catch all) on our own mail server for development/testing. 

maybe you could use something like https://greenmail-mail-test.github.io/greenmail/ or create a mail box on any mail server too. the challenge would be to have the mail headers set correctly. 

https://github.com/hitobito/hitobito/blob/master/doc/e-mail/abo_mails.md

**Comment by olibrian** [comment]
We will close this issue. No action needed. If not, feel free to reopen this issue.
