### ISSUE TITLE
MailCatcher does not work

### ISSUE THREAD

**Issue by maede97** [hitobito/development#5]
I just built all containers from scratch and added a new user (so that I don't have to use the root user, see #3).

I've "sent" a login link to the new user, but this mail does not show up inside MailCatcher. The MailCatcher is running (the website on port 1080 is accessible).

What can I do to solve this?

**Comment by carlobeltrame** [comment]
Looks like we have exactly the same issues ;) I just opened a [PR](https://github.com/hitobito/hitobito/pull/995) in hitobito that should fix this.

**Comment by maede97** [comment]
Thanks, it works now :-)
