### ISSUE TITLE
Rails scheint nicht zu starten?

### ISSUE THREAD

**Issue by masterdot** [hitobito/development#52]
Hallo,

ich bin gerade dabei mir eine lokale Instanz zu erstellen, aber der Webserver scheint nicht zu starten.
               Name                             Command               State                            Ports                        
verein_cache_1             docker-entrypoint.sh memca ...   Up       11211/tcp                                            
verein_db_1                docker-entrypoint.sh --sor ...   Up       0.0.0.0:33066->3306/tcp,:::33066->3306/tcp, 33060/tcp
verein_mailcatcher_1       mailcatcher -f --ip 0.0.0.0      Up       0.0.0.0:1080->1080/tcp,:::1080->1080/tcp             
verein_rails_1             rails-entrypoint.sh rails  ...   Exit 1                                                        
verein_rails_test_core_1   rails-entrypoint.sh sleep  ...   Exit 1                                                        
verein_sphinx_1            sphinx-start                     Exit 2                                                        
verein_webpack_1           webpack-entrypoint.sh /usr ...   Up       0.0.0.0:3035->3035/tcp,:::3035->3035/tcp             
verein_worker_1            rails-entrypoint.sh rails  ...   Exit 1 

Es ist ein ganz frisches debian 12, nach Anleitung hier eingerichtet.
Vielleicht jemand eine Ahnung, was das sein kann?
Danke :)

**Comment by carlobeltrame** [comment]
Kannst du die Logs des Rails Containers hier posten?
```bash
docker-compose logs rails
```

**Comment by masterdot** [comment]
Hallo,
ich habe jetzt den docker erneut aufgesetzt und nun geht es.
Kqnn es sein das rails nicht unter dem root Account startet?
Entweder lag es daran, ist jetzt ein normaler Account ist und nicht root. Oder es ist bei der Installation was schief gelaufen.

**Comment by carlobeltrame** [comment]
Möglich, wir lassen es immer unter non-root laufen, wie es best practice ist. Merci fürs Melden.
