### ISSUE TITLE
Error when executing feature specs in rails-test container

### ISSUE THREAD

**Issue by hupf** [hitobito/development#7]
When executing `rails spec:features` locally within the `rails-test` container, the database is reset and tests will fail with the error `Unknown column 'people.title' in 'field list'` (with generic wagon). In fact the database does no more contain changes from the wagon migrations.

I've been able to make it work, by removing the `:test` group from the `Wagonfile`.

Is this the solution? Or how can this be fixed otherwise?

-> This should be documented.

**Comment by psunix** [comment]
I already removed the :test group from the Wagonfile on my setup. This solved numerous problems for me.

so I created a specific Wagonfile for our dev setup. Let's see how this works
